# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "250071df0934eec37c6c77db0b9f9e4c"
application_url = "https://primarily-incentives-corp-studying.trycloudflare.com"
embedded = true
name = "Barn2 Quanti"
handle = "barn2-quanti"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dhrubok-start.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://primarily-incentives-corp-studying.trycloudflare.com/auth/callback",
  "https://primarily-incentives-corp-studying.trycloudflare.com/auth/shopify/callback",
  "https://primarily-incentives-corp-studying.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://primarily-incentives-corp-studying.trycloudflare.com/api"
prefix = "apps"
subpath = "barn2-quanti"
