# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c5b403fd45b22d3c3f51fd4a9c1fc97d"
application_url = "https://relying-sorted-hungarian-wolf.trycloudflare.com"
embedded = true
name = "Barn2 Bundles & Bulk Discounts"
handle = "barn2-bundles-bulk-discounts"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,unauthenticated_read_product_listings,write_discounts,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://relying-sorted-hungarian-wolf.trycloudflare.com/auth/callback",
  "https://relying-sorted-hungarian-wolf.trycloudflare.com/auth/shopify/callback",
  "https://relying-sorted-hungarian-wolf.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://relying-sorted-hungarian-wolf.trycloudflare.com/api"
subpath = "barn2-bundles-bulk-discounts"
prefix = "apps"

[pos]
embedded = false
