# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "250071df0934eec37c6c77db0b9f9e4c"
application_url = "https://sold-howard-polyester-tragedy.trycloudflare.com"
embedded = true
name = "Barn2 Quanti"
handle = "barn2-quanti"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,unauthenticated_read_product_listings,write_orders,write_products,write_script_tags,write_discounts"

[auth]
redirect_urls = [
  "https://sold-howard-polyester-tragedy.trycloudflare.com/auth/callback",
  "https://sold-howard-polyester-tragedy.trycloudflare.com/auth/shopify/callback",
  "https://sold-howard-polyester-tragedy.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://sold-howard-polyester-tragedy.trycloudflare.com/api"
subpath = "barn2-quanti"
prefix = "apps"

[pos]
embedded = false
