# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "858c89ba09011b7be4c42d83ef959102"
name = "Barn2 Bundles & Bulk Discounts"
handle = "barn2-bundles-bulk-discounts"
application_url = "https://shopify-quantity-discounts.fly.dev"
embedded = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

  [[webhooks.subscriptions]]
  topics = [ "shop/update" ]
  uri = "/webhooks/shop/update"

  [[webhooks.subscriptions]]
  topics = [ "themes/update" ]
  uri = "/webhooks/themes/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_themes,unauthenticated_read_product_listings,write_discounts,write_orders,write_products,write_script_tags"

[auth]
redirect_urls = [
  "https://shopify-quantity-discounts.fly.dev/auth/callback",
  "https://shopify-quantity-discounts.fly.dev/auth/shopify/callback",
  "https://shopify-quantity-discounts.fly.dev/api/auth/callback"
]

[app_proxy]
url = "https://shopify-quantity-discounts.fly.dev/api"
subpath = "barn2-bundles-bulk-discounts"
prefix = "apps"

[pos]
embedded = false
