-- CreateTable
CREATE TABLE "Session" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "shop" TEXT NOT NULL,
    "storeName" TEXT,
    "state" TEXT NOT NULL,
    "isOnline" BOOLEAN NOT NULL DEFAULT false,
    "scope" TEXT,
    "expires" DATETIME,
    "accessToken" TEXT NOT NULL,
    "volumeDiscountFunctionId" TEXT,
    "storeDiscountMetaFieldId" TEXT,
    "userId" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "email" TEXT,
    "url" TEXT,
    "shopOwnerName" TEXT,
    "accountOwner" BOOLEAN NOT NULL DEFAULT false,
    "locale" TEXT,
    "collaborator" BOOLEAN DEFAULT false,
    "emailVerified" BOOLEAN DEFAULT false,
    "currency" TEXT,
    "timezone" TEXT,
    "planDisplayName" TEXT,
    "isPartnerDevelopment" BOOLEAN DEFAULT false,
    "isShopifyPlus" BOOLEAN DEFAULT false,
    "moneyFormat" TEXT,
    "moneyInEmailsFormat" TEXT,
    "moneyWithCurrencyFormat" TEXT,
    "moneyWithCurrencyInEmailsFormat" TEXT,
    "checkoutApiSupported" BOOLEAN DEFAULT false
);

-- CreateTable
CREATE TABLE "DiscountBundle" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT '',
    "previewEnabled" BOOLEAN NOT NULL DEFAULT false,
    "whichProducts" TEXT NOT NULL DEFAULT '',
    "layout" TEXT NOT NULL DEFAULT '',
    "priority" INTEGER NOT NULL DEFAULT 0,
    "active" BOOLEAN NOT NULL DEFAULT false,
    "shopifyDiscountId" TEXT,
    "sessionId" TEXT NOT NULL,
    "selectedProducts" TEXT,
    "selectedCollections" TEXT,
    "excludedProducts" TEXT,
    "excludedCollections" TEXT,
    "volumeBundles" TEXT,
    "pricingTiers" TEXT,
    "discountCalculation" TEXT,
    "activeDates" TEXT,
    "specificDates" TEXT,
    "storeDisplay" TEXT,
    "designOptions" TEXT,
    "customDesigns" TEXT,
    "previewOptions" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "DiscountBundle_sessionId_fkey" FOREIGN KEY ("sessionId") REFERENCES "Session" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);
